import pandas as pd
import matplotlib.pyplot as plt

from analysis import get_stats
from visualize import (
    plot_cost_and_attempts,
    plot_with_vs_without_stone,
    plot_item_comparison,
    plot_delta_weapon_analysis,
    plot_distribution
)


def main():
    # Load dataset generated by simulation
    df = pd.read_csv("data.csv", sep=";")

    # Aggregate statistics (mean cost and attempts)
    stats = get_stats(df)

    # --- Generate visualizations ---

    # Overall system behavior (log scale)
    fig1 = plot_cost_and_attempts(stats)

    # Stone impact (Physical Weapon)
    fig2 = plot_with_vs_without_stone(stats, "Physical Weapon")

    # Magic vs Physical comparison
    fig3 = plot_item_comparison(stats, "Magic Weapon", "Physical Weapon")

    # Stone impact (Full Armor)
    fig4 = plot_with_vs_without_stone(stats, "Full Armor")

    # Delta / growth analysis
    fig5, fig6 = plot_delta_weapon_analysis(stats, "Physical Weapon")

    fig7 = plot_distribution(df, "Physical Weapon", 16, "total_enchant_cost", log=True)

    # Show all figures
    plt.show()


if __name__ == "__main__":
    main()